### ISSUE TITLE
Governance

### ISSUE THREAD

**Issue by DavidTPate** [RiptideElements/contrib#2]
As part of this effort we need to set some general guidelines for the management of the repositories and how things are decided. Below is a draft with many parts shamelessly borrowed from Hapijs because I think they've done a good job.

Current Draft:

## TL;DR
Riptide Elements which includes repositories under [RiptideCloud](https://github.com/RiptideCloud) and [TryxAPI](https://github.com/TryxAPI) is run by the lead maintainers of its repositories. Decisions are made by consensus whenever possible. If consensus is not possible, the lead maintainer of the relevant repository has the final say. Lead maintainers cannot be removed unless they leave or hand over the repository to someone else. However, repositories can be forked. The entire project is run by consensus by its lead maintainers.

# Organization Governance
This document defines the rules and processes through which the **Elements** community makes decisions and shares control and leadership. The governance model was designed to follow the spirit and tradition of open source by embracing consensus, forking, and individual ownership as its building blocks.

## Principals
* Riptide Elements is a partially open, inclusive, and tolerant community of people working together to build a best-in-class set of node.js modules and systems.
* We value diversity of individuals and opinions, and seek to operate on consensus whenever possible.
* We strive to maintain a welcoming, including, and harassment-free environment throughout the organization, regardless of the form of communication.
* When consensus is not achievable, we defer to the individual owners of each module to reach a conclusion; the powers of the individual owner are kept in check by the ability of the community to fork and replace its dependencies on the individual module and maintainer.

## Structure
Every organization activity is structured in the form of a repository. This includes (but not limited to) modules, discussions, web sites, and events. **Elements** repositories must reside within the **Elements** organizations and under its control.

### 
Each organization repository belong in one of two groups:

* Core - the **Elements** module as well as any **Elements** module **Elements** depends on.
* Community - any repository **Elements** does not depend on.

## Lead Maintainers
Each repository is assigned a lead maintainer. Lead maintainers act as the repository's BDFL (benevolent dictator for life) and are responsible for the daily operations of the repository, for seeking consensus, and for making the final decisions when consensus cannot be achieved. For modules, they have the npm publishing rights and the final say on releasing new versions.

Lead maintainers cannot be removed unless they leave, assign their position to someone else, or have become inactive for 30 days and fails to respond to attempts to communicate, at which point a new contributor will assume responsibility for the repository. There are no other ways to remove a lead maintainer as long as the repository remains part of the **Elements** organizations.

The **Elements** organization is managed by its lead maintainers in two groups based on the designation of each repository (core and community):
* Core contributors - are those who maintain **Elements** or one of its dependencies. Core contributors work together to guide the core framework, make decisions about releases and breaking changes, and are responsible for the daily maintenance of the core repositories. They also decide to accept or create new repositories, as well as remove repositories from the organization. The core contributors operate on consensus only on all matters not specific to an individual repository. When no consensus is possible, the status-quo remains. Each core contributor has the final say over the repositories they lead, including the modules the repository depends on. Core contributors have full read/write/admin access to all the core repositories.
* Community contributors - are all the lead maintainers of repositories within the organization. Each community contributor has the final say over the repositories they lead, including the modules the repository depends on. Community contributors have full read/write/admin access to all the community repositories.

## Elements Lead maintainer

By the virtue of the lead maintainer's powers, the lead maintainer of the **Elements** repository can affect the designation (core and community) of each repository (and its lead maintainer) by making changes to the module's dependencies. They have no other powers, cannot remove or add modules to the organization without core contributors consensus, or make any other decisions outside the scope of the **Elements** repository.

**Comment by TylerDixon** [comment]
One thing we should think about is how we want to handle course/app related materials. This being along the lines of templates, activities, application specific controllers, etc.

**Comment by TylerDixon** [comment]
How do we want to handle libraries that need to be built before tagged? Should it be built in the PR, and then merged in? Or should the maintainer merge in, build the project, and tag if need be?

**Comment by DavidTPate** [comment]
I'm thinking the right way to do it would be for whomever merges it go handle building. The reason why is that we may have multiple PRs coming in for a single release and this way we would reduce potential merge conflicts (compared to if all PRs build before submitting the PR).
