### ISSUE TITLE
Guidelines

### ISSUE THREAD

**Issue by DavidTPate** [RiptideElements/contrib#3]
As part of this effort we want to establish some general guidelines for running our project and organization, again much of this is shamelessly borrowed from Hapi due to it being good. Below is the current draft:

# Running an Elements Repository
The purpose of this document is to outline procedures and guidelines for the operation of a repository under the **Elements** umbrella. The number of modules and repositories under the **Elements** organization will continue to grow so it is important that every repository has a certain amount of parity. This allows for the community to instantly have a level of familiarity regardless of the repository they are working in.

## Labels
Every **Elements** repository should make generous use of labels. Labels help to make triaging issues easier. Below is the list of labels that every repository should be using and a brief explanation of the intent of the label.

* `breaking change` - tag issues and pull requests with this change if, when the code is merged, it will cause a breaking change in the current version. `breaking change` issues should be attached to the appropriate milestone.
* `bug` - issues that have been *confirmed* (with reproducible steps) to be bugs in the code should be tagged with `bug`.
* `dependency` - if the issue or pull request addresses a dependency issue, it should have the `dependency` tag. Any module that is running in production should have a version >= 1.0.0 and all of it's dependencies should follow suite.
* `discussion` - this tag gets applied to issues that are ideas or requests from the community that need active input from other community members and possibly the Lead Maintainer.
* `enhancement` - non-breaking changes that would generally require a bump in the minor version number.
* `help wanted` - issues where the **Elements** team is actively requesting community feedback should be tagged with `help wanted`.
* `new contributor` - tasks that are sufficiently small and easy for new contributors to complete, and which collaborators don't mind assisting new contributors in completing.
* `non-issue` - this label is used when a user reports something that they perceive as a bug in an **Elements** module but ultimately ends up being a user error. Often, issues tagged with `non-issue` will lead to updated documentation or additional validation.
* `question` - generic label for user questions.
* `release notes` - if the changes to a module are really broad, a new issue should be created and labeled with `release notes`. The issue should document what the changes are, how it impacts existing code and how to migrate to the next version.
* `request` - issues that are asking for specific changes and have been approved by the community or **Elements** team, should have the `request` label applied to them. This label can be useful for people looking for ways to contribute to the **Elements** ecosystem.
* `security` - issues that improve or fix existing security deficiencies should be labeled with `security`.

## Milestone
Milestones are used to keep track of future releases. Both issues and pull requests related to the future release should have a milestone attached to them. Milestone names should be the same as the semantic version of the module. Once all of the attached issues and pull requests are completed, a new version of the module should be published to the npm registry. The milestone is then considered "complete" and should be closed.

## Releases
In the **Elements** universe, we take releases very seriously because we are maintaining enterprise-grade software. We strictly adhere to semantic versioning for all versions. When a milestone is completed, the Lead Maintainer will go through the following steps:

1. Make sure the local master branch is 100% up to date with upstream:master.
1. Run npm publish in the command line to update the npm registry.
1. Tag the version just published to npm. Run git tag -a vx.y.z -m "version x.y.z" where x.y.z matches the version key in "package.json". The format of the tag and the message should match exactly as in the example.
1. Update the tags in the upstream remote via git push upstream --tags.

## Issues
Issues can be created by anyone with a GitHub account. They should be tagged by any **Elements** organization members with access. Issues can be closed by the original requester, any member of the Core team, and the Lead Maintainer. Conversely, a Core team member or the Lead Maintainer can reopen issues at their discretion. It is important to keep issues maintained as it provides a task list for the community of contributors.

Issues that are closed with a pull request should be linked together to keep the "paper trail" intact.

Be mindful when closing issues as it is one of the primary ways we, as an organization, communicate with the community. Try to make sure the issue has been sufficiently resolved before closing it. In other words, don't be a jerk about closing issues.

## Retiring
Sometimes one of the **Elements** modules becomes outdated or obsolete. At that time, the team will decide the next steps to take with the module. If the team has decided that the module is no longer useful, it will be immediately retired. If the module is still useful by the general community, a request for a new maintainer will be sent through the normal communication channels. If no one volunteers to take over the project after one week, it is retired.

If a new maintainer does volunteer, the repository ownership is transferred out of the **Elements** organization to the new maintainer. The license must be updated to remove any mention of Riptide or Elements.

1. "README.md" is updated with the "Retired" image and the message "No longer being maintained". A link should also be added that points to the last version's "README.md".
1. Tag all open issues with the "deprecated" tag and then close them. Disable issues globally in the repository settings.
1. Bump the minor version of the module in "package.json".
1. The Lead Maintainer should then follow the steps for releases.
1. The Lead Maintainer should issue an npm deprecate command and deprecate all versions of the module.

**Comment by TylerDixon** [comment]
We should add some notes about keeping a changelog for modules, which could at the very least just be lists whenever we create new tags. Especially for breaking changes.

**Comment by DavidTPate** [comment]
@TylerDixon Yeah, the changelog should be covered through the "Releases" section.

**Comment by Jhorlin** [comment]
@DavidTPate for dependency tag. Any module that is running in production should have a version >= 1.0.0. Internally we can say any module we use cannot go into production  until the version is >=1.0.0 but what about a 3rd party module would we ignore this rule? how do we enforce this outside our group?

**Comment by Jhorlin** [comment]
@DavidTPate currently all of our tags are not prefixed with a v. In your example you state
Run git tag -a vx.y.z -m "version x.y.z" .  Are you proposing we prefix tags with v?

**Comment by DavidTPate** [comment]
@Jhorlin Both of those pieces were taken directly from Hapi and I just left them there to see what you guys thought.

Versions being >= 1.0.0 is more of a way to try and weed out things that are either very new or not well supported. The [gulp istanbul](https://github.com/SBoudrias/gulp-istanbul) plugin that we use for example is version `0.6.0` and hasn't been updated in almost a year. Because of this it could cause issues should istanbul/mocha have updates. It's definitely not perfect, but an easy way to try to weed out the things that you should ignore.

As for the versions such as `vx.y.z` the reason why it is like that is because that is how semantic versioning is defined. I think we should switch to that method.

**Comment by Jhorlin** [comment]
@DavidTPate Agreed For my next tag I will continue the next Increment of the tag but prefix it with a v.

**Comment by TylerDixon** [comment]
Here's a pattern I started adopting for my notes when tagging. I don't know if this is something we want to standardize, this is just what I've started to do:
- - - - - - - - -
```markdown
<short description summarizing the updates with the tag>
## Changelog
### Features
* **Module Updated** - Description of change made to module
* **Module 2 updated**
  * Sublist of items for multiple updates made to a module
  * More updates

### Breaking Changes
* **Module with breaking change** - description of breaking change, can do sublist as well

### Bugfixes
* **Module with bugfix** - description of bugfix, can do sublist as well

### Misc changes.
* For changes that don't fit an above category
```

And here's how it looks:
 - - - - - - - -


This tag implemented ____ with ______.
## Changelog
### Features
* **Module Updated** - Description of change made to module
* **Module 2 updated**
  * Sublist of items for multiple updates made to a module
  * More updates

### Breaking Changes
* **Module with breaking change** - description of breaking change, can do sublist as well

### Bugfixes
* **Module with bugfix** - description of bugfix, can do sublist as well

### Misc changes.
* Updated tests to use `chai-as-promised`
